remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Personal academic and research website of Inigo Lopez Gazpio
description: Welcome to the personal, academic and research website of Inigo Lopez-Gazpio
show_downloads: true
google_analytics: UA-31935166-2
collections:
  pages:
    output: true
    permalink: /_pages/
